apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 309191981782.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:92b5341a52ecc6b0e3e201187c82f0c0ff5e9179
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlemusic-service
  labels:
    app: googlemusic
spec:
  type: ClusterIP
  selector:
    app: googlemusic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
