apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobiles-deployment
  labels:
    app: mobiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobiles
  template:
    metadata:
      labels:
        app: mobiles
    spec:
      containers:
      - name: mobiles
        image: 684160548236.dkr.ecr.us-west-2.amazonaws.com/shopping-site-mobiles:9a578a55d81145f13426e45f87993d0a313d7cf8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mobiles-service
  labels:
    app: mobiles
spec:
  type: ClusterIP
  selector:
    app: mobiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
