apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-deployment
  labels:
    app: fashion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion
  template:
    metadata:
      labels:
        app: fashion
    spec:
      containers:
      - name: fashion
        image: 309191981782.dkr.ecr.us-west-2.amazonaws.com/shopping-site-fashion:92b5341a52ecc6b0e3e201187c82f0c0ff5e9179
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-service
  labels:
    app: fashion
spec:
  type: ClusterIP
  selector:
    app: fashion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
